# -*- coding: utf-8 -*-
"""Múltiples filtros en videos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WbcEnWZAZeiFo7rJqsR8kDESX4sIH0BA
"""

from google.colab import files
import cv2
import os

uploaded = files.upload()
video_name = list(uploaded.keys())[0]

frames_dir = "frames_input"
os.makedirs(frames_dir, exist_ok=True)

cap = cv2.VideoCapture(video_name)

fps = cap.get(cv2.CAP_PROP_FPS)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

frame_count = 0
while True:
    ret, frame = cap.read()
    if not ret:
        break
    frame_path = os.path.join(frames_dir, f"frame_{frame_count:05d}.jpg")
    cv2.imwrite(frame_path, frame)
    frame_count += 1

cap.release()
print(f"Video cargado: {frame_count} frames extraídos | {fps} FPS | {width}x{height}")

print("Filtros disponibles:")
print("  1. Inversión de colores (Negativo)")
print("  2. Blur")
print("  3. Recorte")
print("  4. Imagen binaria")
print("  5. Detección de bordes (Sobel)")
print()
print("Escribe los números de los filtros que deseas aplicar separados por coma.")
print("Ejemplo: 1,3,5")

seleccion = input("Filtros a aplicar: ")
filtros_seleccionados = [int(x.strip()) for x in seleccion.split(",")]

if 3 in filtros_seleccionados and len(filtros_seleccionados) > 1:
    print("⚠️ El filtro 3 (Recorte) no puede combinarse con otros filtros. Será ignorado.")
    filtros_seleccionados.remove(3)

kernel_size = None
threshold = None
x_start = y_start = width_crop = height_crop = None

if 2 in filtros_seleccionados:
    kernel_size = int(input("Blur - tamaño del kernel (ej: 3, 5, 7): "))

if 3 in filtros_seleccionados and len(filtros_seleccionados) == 1:
    print(f"Dimensiones del video: {width}x{height} (ancho x alto)")
    x_start = int(input("Recorte - x_start: "))
    y_start = int(input("Recorte - y_start: "))
    width_crop = int(input("Recorte - width_crop: "))
    height_crop = int(input("Recorte - height_crop: "))

if 4 in filtros_seleccionados:
    print("Umbral: T=64 mayormente blanco | T=128 equilibrio | T=192 mayormente negro")
    threshold = int(input("Binario - umbral T (0-255): "))

print()
print(f"Filtros seleccionados: {filtros_seleccionados}")

import numpy as np
from numba import cuda
from numba import config
config.CUDA_ENABLE_PYNVJITLINK = 1

@cuda.jit
def invert_kernel_2D(img_color, img_inverted):
    j, i = cuda.grid(2)
    rows = img_inverted.shape[0]
    cols = img_inverted.shape[1]
    if i < rows and j < cols:
        img_inverted[i, j, 0] = 1.0 - img_color[i, j, 0]
        img_inverted[i, j, 1] = 1.0 - img_color[i, j, 1]
        img_inverted[i, j, 2] = 1.0 - img_color[i, j, 2]

@cuda.jit
def blur_kernel_2D(img_color, img_blurred, kernel_size):
    j, i = cuda.grid(2)
    rows = img_color.shape[0]
    cols = img_color.shape[1]
    if i < rows and j < cols:
        r = kernel_size // 2
        total_r = total_g = total_b = 0.0
        count = 0
        for di in range(-r, r + 1):
            for dj in range(-r, r + 1):
                ni = i + di
                nj = j + dj
                if 0 <= ni < rows and 0 <= nj < cols:
                    total_r += img_color[ni, nj, 0]
                    total_g += img_color[ni, nj, 1]
                    total_b += img_color[ni, nj, 2]
                    count += 1
        img_blurred[i, j, 0] = total_r / count
        img_blurred[i, j, 1] = total_g / count
        img_blurred[i, j, 2] = total_b / count

@cuda.jit
def crop_kernel_2D(img_color, img_cropped, x_start, y_start):
    j, i = cuda.grid(2)
    rows = img_cropped.shape[0]
    cols = img_cropped.shape[1]
    if i < rows and j < cols:
        img_cropped[i, j, 0] = img_color[i + y_start, j + x_start, 0]
        img_cropped[i, j, 1] = img_color[i + y_start, j + x_start, 1]
        img_cropped[i, j, 2] = img_color[i + y_start, j + x_start, 2]

@cuda.jit
def binary_kernel_2D(img_color, img_binary, threshold):
    j, i = cuda.grid(2)
    rows = img_binary.shape[0]
    cols = img_binary.shape[1]
    if i < rows and j < cols:
        intensity = (img_color[i, j, 0] + img_color[i, j, 1] + img_color[i, j, 2]) / 3.0
        img_binary[i, j] = 1.0 if intensity > threshold else 0.0

@cuda.jit
def grayscale_kernel(img_color, img_gray):
    j, i = cuda.grid(2)
    rows = img_gray.shape[0]
    cols = img_gray.shape[1]
    if i < rows and j < cols:
        img_gray[i, j] = 0.2989 * img_color[i, j, 0] + 0.5870 * img_color[i, j, 1] + 0.1140 * img_color[i, j, 2]

@cuda.jit
def sobel_kernel_2D(img_gray, img_edges):
    j, i = cuda.grid(2)
    rows = img_gray.shape[0]
    cols = img_gray.shape[1]
    if i > 0 and i < rows - 1 and j > 0 and j < cols - 1:
        Gx = (img_gray[i-1, j+1] + 2.0 * img_gray[i, j+1] + img_gray[i+1, j+1]) - \
             (img_gray[i-1, j-1] + 2.0 * img_gray[i, j-1] + img_gray[i+1, j-1])
        Gy = (img_gray[i+1, j-1] + 2.0 * img_gray[i+1, j] + img_gray[i+1, j+1]) - \
             (img_gray[i-1, j-1] + 2.0 * img_gray[i-1, j] + img_gray[i-1, j+1])
        G = cuda.libdevice.sqrtf(Gx * Gx + Gy * Gy)
        img_edges[i, j] = min(G, 1.0)

print("Kernels CUDA definidos correctamente.")

import cv2
import os

frames_dir = "frames_input"
frames_output_dir = "frames_output"
os.makedirs(frames_output_dir, exist_ok=True)

frame_files = sorted(os.listdir(frames_dir))
total_frames = len(frame_files)
total_filtros = len(filtros_seleccionados)
frames_por_segmento = total_frames // total_filtros

out_width = width
out_height = height

def get_grid(rows, cols):
    threadsperblock = (16, 16)
    blockspergrid_x = (cols + threadsperblock[0] - 1) // threadsperblock[0]
    blockspergrid_y = (rows + threadsperblock[1] - 1) // threadsperblock[1]
    return (blockspergrid_x, blockspergrid_y), threadsperblock

for idx, fname in enumerate(frame_files):
    segmento = min(idx // frames_por_segmento, total_filtros - 1)
    filtro_actual = filtros_seleccionados[segmento]

    frame = cv2.imread(os.path.join(frames_dir, fname))
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    img = frame_rgb.astype(np.float32) / 255.0

    ROWS, COLS, COLOR = img.shape
    blockspergrid, threadsperblock = get_grid(ROWS, COLS)

    if filtro_actual == 1:
        d_in = cuda.to_device(img)
        d_out = cuda.device_array((ROWS, COLS, COLOR), dtype=np.float32)
        invert_kernel_2D[blockspergrid, threadsperblock](d_in, d_out)
        img = d_out.copy_to_host()

    elif filtro_actual == 2:
        d_in = cuda.to_device(img)
        d_out = cuda.device_array((ROWS, COLS, COLOR), dtype=np.float32)
        blur_kernel_2D[blockspergrid, threadsperblock](d_in, d_out, kernel_size)
        img = d_out.copy_to_host()

    elif filtro_actual == 3:
        xs = max(0, min(x_start, COLS - 1))
        ys = max(0, min(y_start, ROWS - 1))
        wc = min(width_crop, COLS - xs)
        hc = min(height_crop, ROWS - ys)
        blockspergrid_c, threadsperblock_c = get_grid(hc, wc)
        d_in = cuda.to_device(img)
        d_out = cuda.device_array((hc, wc, COLOR), dtype=np.float32)
        crop_kernel_2D[blockspergrid_c, threadsperblock_c](d_in, d_out, xs, ys)
        img = d_out.copy_to_host()

    elif filtro_actual == 4:
        threshold_norm = threshold / 255.0
        d_in = cuda.to_device(img)
        d_out = cuda.device_array((ROWS, COLS), dtype=np.float32)
        binary_kernel_2D[blockspergrid, threadsperblock](d_in, d_out, threshold_norm)
        img_gray = d_out.copy_to_host()
        img = np.stack([img_gray, img_gray, img_gray], axis=-1)

    elif filtro_actual == 5:
        d_in = cuda.to_device(img)
        d_gray = cuda.device_array((ROWS, COLS), dtype=np.float32)
        d_edges = cuda.device_array((ROWS, COLS), dtype=np.float32)
        grayscale_kernel[blockspergrid, threadsperblock](d_in, d_gray)
        cuda.synchronize()
        sobel_kernel_2D[blockspergrid, threadsperblock](d_gray, d_edges)
        img_edges = d_edges.copy_to_host()
        img = np.stack([img_edges, img_edges, img_edges], axis=-1)

    frame_out = (img * 255.0).astype(np.uint8)
    frame_out_bgr = cv2.cvtColor(frame_out, cv2.COLOR_RGB2BGR)
    cv2.imwrite(os.path.join(frames_output_dir, fname), frame_out_bgr)

print(f"{total_frames} frames procesados | {total_filtros} filtros | ~{frames_por_segmento} frames por segmento")

import cv2
import os
from google.colab import files

frames_output_dir = "frames_output"
output_video_name = "video_filtrado.mp4"

frame_files = sorted(os.listdir(frames_output_dir))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video_name, fourcc, fps, (out_width, out_height))

for fname in frame_files:
    frame = cv2.imread(os.path.join(frames_output_dir, fname))
    out.write(frame)

out.release()
print(f"Video generado: '{output_video_name}' con {len(frame_files)} frames | {out_width}x{out_height} | {fps} FPS")

files.download(output_video_name)